apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
spec:
  encryptedData:
    notifiers.yaml: AgBR+4vWZEqO5Z5jYbDL/SQHcRkvfsxIaXIl8dZ7NfKoe656xg4XoeTu7MiNf9Y1HX1TakORqxlxIK9A8x1vUxcIVyA+VLljVHQEtz7h72xwGtcmxwGNQUoliyNu9aNjRxB7zjR+nvdTpiJLJwEoSwN0ZUXUZYuZfMIgUMsqPcdcq2KuWNeuBmzX5G1YMvqa7bdwevmXyeEozcEE76E5WvDlnSQ5Oxu5nE5aR/OuDvE+FYxNcPgmkt13/nLrfQAy8G6snuzdrktxxVk4hWGuC/wMng92a/MLdhHdQzx2gplAvqFeZYtLW13Ni12vA8DGJqCHKRh4LK1RK+MDI19jl/WtY2q2YVEEuYKWpyaRZjrinkJnuSn4vVj19aLXIwHUOeLs25uW+w8oMxX9JgNtM2+agXp3Wz6fuXLrUTZ4+hfCJMj0uHFKk1h4VxvPjYcCtN0vrkhbGyFURC4VM3FAPvMroZPoswtm6SPySqbg3Hpr+llcz0PnIYaKpJyLCc5SUqd9QyRvGVPowhu+PjE8Co5KGX6h7HU+LlsGAdvUifY7ZHpebvHVKXbH9pKDzZd9mM9PF18JmaQM9xFVmYRXQhlCDiWQu7/fFXvlmyww8pc9wV97kmvoDOVXHi1BFTZImCfThDYXBiPAIjwu245Ye5GscKDb2eC5TS0a7PQ8PFP4ekSFDLEMzpJ/P6tSnvuG6RyMXZDo63x+Ok2wt5Ib4JIh4VjLPOAqMykkKMqYeKKKMwZAV/QOLT+HWLttquc9qtUa6rWLmSYnR5hDL/h2xBOmLStzF4hAjTYBzPB6k14V4OMTXpZHnCpxkqtOzPPGqlNmj2fT/rlC6nveR4NsiVHXK6dVWfDzrUpZIRTYguMO0ADc7Vgep5U3+CCTf8Vn
  template:
    metadata:
      name: argocd-notifications-secret
