apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
spec:
  encryptedData:
    telegram-token: AgBjHmpUCmxeFi41wwL4Y1WCwGvhEWFX8AemRsyM/OioU8oYruXRAjHCmWE+etvzRohhCPx9n+rVPW7uQ6cpFT16/LuHDN1QOsb3W8rjiC0lqluj/rmVQ7Wcj5+pBzhajegJSXOH5AZjQWn/SviZf+gXOAkeWdVE8g7mVnczUIpSdphQaAZWp+Cg8eBSjq6nfVq7TP0Hx4xvz4WgUwPwfflT1lBuqmKN5bDDApeUckfzJjowv5tTOGPATEj8QWKZSrPrt/xmlWlfZHjv482IyyZUf2vfqETwz21KWl8Da4eNCdSUwKNeICge0funPdiN+eUKCeZW6ZifyCXzOYy8EpGl65G5Lxi2r5p8tO81Bn+brORGin/ZGeL+cdST4p+3NZis7cBnG94jwNNPIOd3P9MxbOxhVwI71cg2OYlUXbLrKTNSWZHS6Q2jZNQJlnozYXgXkUprUJZqTacwK7vuWkVbCCv6uZlf/UT6c9+N4RS9Nhkxs2dKQMQfbMR3vjxUbWmTQm5oo/f+yBaKO5UCr7oZ3r0qkoTDJWAAY+1ODtacxXWVFioJR0wCj5bGU0GWX006DNLuOd0xzPRcyBohP/k0CI9HV4zgF5E/oB+XOH9qZtj1EVz1Od32BPLuDWzugtEeyV+OrXkWyVk9J06Xk1K6dveaco6Wem6YqY0FCLd2iPDYMDtu2Wd4tL+dgo6v/CoCg5zfHWdxwDDW1AuWAssFFb4+6oGxccA9BMTlH98ZBYiqThenoA1ZTSb+Non9    
  template:
    metadata:
      name: argocd-notifications-secret
