apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: code-server
spec:
  encryptedData:
    password: AgCky8TOjp3I7Cgovd9qHPaUY/2UTHwpixgsoW0GZGcl6lZRYeExmjrCRS5f91LIGk4U7uGOjHs2+XVe53cLVwot2HaSt9ZADnJnN9qUJRfViGMZLAtJ/d6BXOtfkmTxN3sFon3Bj0OLsyKwby7j+CnGwOcMX5aGeDUuCDFcg9pWp58XkytsYpzISYgpyygaV4XaGeTaduCaN8pwdGQ5s3ULbMWE3HnJRs6nT2U7ofxhxP3qwYxZIjRgMWldDV8fOakyzS2v61NlAUZ6yGzEUJQiJl+Etf/aTa6Egd2viiLI3uOznvy2UK+YiVMB7mZ3LIJIA55rTm6F7NqMvQx/mT2z5l1bnp7NEgbqbnCQe1XIOIePRMAwJNjSe7MH+8axHluPLQyCen50l6deVekzcfo9ueXnirMOKmnbDpwUe6lSDc54xi1ZZIf+Lgux6ROTfZphaKQN9KTRCINDaTW9YF5eW/frkZlOlHYncZIrUjgZdbb85zzAn4xsx8weqtLuxYITmlJ/FqNCFwNtaCIZxFnoybr7RGbJHcxKYCiDMyoELeDB7vNTgFOX3CKg+GgrQrOP4cLAqA8d/aJAesFkhAg/ycWdALofAme/Xf4Igtf3arnETwdSQjqjUc85mqNqJU0ievI1LfLC5HzWhuHbiAYCBrpacbpHLH+g/4dFd3RKoKv+luRCUl4atJdINskXKJwHyPvrIpIlcrgOroF3+AYiXaIebPgaZtiC1b5jKMpfbQ==
  template:
    metadata:
      name: code-server

