apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: code-server
spec:
  encryptedData:
    password: AgArVHWpTDnEMXWufKuLhN6BHbq1hvrL9MvbqoE+fADcVhAHgz+eP/zE7wc7FERrgYP681zme0pzilk5GRy4unwaXKcMYmfbROK2jiQNwgwoiBKcRoDBKb2SSXjVwoP/09QDC6spTxmgwCDpKaE8/NvEXWtRK6zMfkGl0IHQmlHtUs1qvzzXXZeaHKS99nWrUhKt5VGSc6pgDRL3D5CzVW1ECDbUvG8M6E7DLdGCju3ek/85fhbS3Q5yi/vbgICFdT1WzzTRDy1X7Va3DSPt+8fNW7RGqKVaSULjVre+5fuPSJ4KoEktKaylq7VbKKs4Lz/PqECysleZhYYvWrYxGzYoH87x0EY/y+XkTJTR3uvT1c/NCng5LwauJTE/5RS/vfpsB0xThzuKCIZpLFHE1E+67ddwo9ztCw5gBmVH6iqv2riWlHF+n615J+DnThYk/AlKj3lrUaztSoQwbuzLITSBpbpY5hyIyVLw4y6Oms521HJlh67raB4BWsrTU6PJAZRPTUZjB9TcnTHGUUYfA60/afL7MHbkuEtsjzPKZqmTHyaa0dAg45Q6/W9sMjPAkKZuUFtflF5eUf5PIfwp2TEIx7ysw/qEiCjl3w8HcKbU/xNzXDarNbyPxDHt1YbIo4dnr+YlbS0MxYvm0Q0yRwemuibTaWIgETR1plx5svaJEknI06UdAzllXST127wP/3IuHx6lVuDiGqgH3QE+rOMDAWpMovAmOdyGnZRI+1cO7g==
  template:
    metadata:
      name: code-server

