apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: grafana
spec:
  encryptedData:
    admin-user: AgA7JIC+8wMEo8y35r9VHqnPa3mIoESkDQEoYSflKXOCv9ukIcWZ28hYficMdKFG6u6X1m+Qsus8Nr1r2DJaEL+7os+djGaGO+suNGNc2SlSW+tm4FHPc3b3VJYJFxL9pxdW4W7dyjT6dKXdBotrY4hZBakC9+KxthI1iXmhZPD27bONEHJpVdd+zhTFgfF4iM2W8CGGLENWnmiou57QvIUyfWgZTWYTfYzyLq9TmvJurIqn+Ni5ErXGTkBYqDB0HUgG+q9KywWmG+HdM9bEq9Dipr5EKnUSXl3khiZ3fK0xg4Ta6F+tt1XtpK9vDIxpahWduC0xeVftKZ9nCgTISU/GBSXD+rKP+VfYDoTdqEOHlunNk5sHJNPfn7kZfESGvGghJT/3ayTiAGSAZNxYtk2zmCXOWtqTsNWGoJA6OB0D0mtfxwbM1fAXIAC44NfBZ6NOaUJU+GpXJdsGejpzl46vt9LiX+a1COjd2Y39eLgr8nc2k9/6r1xXxIMC43yfwR/mDXl7nd0pL2A58DI+rTOod6fS0ruGhMQPTr5FYoVBQ2D5Hg0hTixlKOcCkfxX6w9G0AOHDg5vsW+zOCF+UepPAYf7acXVQA/TkLlir8pxA/zeplPYTqENSj9me6cfOT2tGm4SqW9pZ9WANKPHDU40PDwv+JnoIcPgVgTPsMi8N/QBVa3J69UqfU1ZuEMob4EeIji+gQ==
    admin-password: AgByck3Q5rgVscyBwr1+s8i29At+zZZgTmylM4bFGSAEROAsGEoTMjVBVVbjJzIK6cEUNYw6D8vpcyJ/n+nFwnqTSlp5+1T8L1qmFRK4bZgUPvkRO+RlIeL1YE/NBkXboAGA9xyzutMYuTpwnU2wbCSvSvqHaGn9kP+zyjKsDpRnTdPQzafkkA2vP+SES4jQO3T/BHc9p8Q4LnSdz7a23oxsQ/m6OXTT6yJAkXJ6c1CnjU4za+0B8nPg4VyF37Upke+gnCtYTtgPqmm62HDAqu+NH9NljiRFE1CxV9Of0su67f2MmwFyS2sioXmVREy39BNO+PMBFPpoLJrA9j81j8SBGrjpj0dKNXT0qUHZzdL06fhyin1mcABo2iO3iSYqgg9Q32Ih6s0s7+s1v4a7J6NbRpjM84seUJ2IP18t3ceYZd1kkardtr6TQw9naPvuVdNPiJ4OU9aGAykE1H9px+5wBk6Z1v1cTQrPBqCv/SUZUWDeK/WWnXIm5O2EziG/qU0TBMI9ySJ5swryjLVm7cORX975x843PWG6DCkm3SJm3QTSnUkwcyCCPcJTUc4jGMkSPzcYu/odIQNpwTDdYHXL0eDTImkoxR1+npFjQxQlB82iYe+yF5k2CrMMA8doP9JPBxHfxeIQM0Hx/Cvgksa7T/HjO2GaPSUWILsfMdq5dyLL+YWCNOC8chBUOHxAHFK3DdFa5OV515Rx3gHf+E5yGNM0
  template:
    metadata:
      name: grafana
      namespace: grafana
