apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: support/metallb
    repoURL: https://github.com/mattsve/k8s
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true