postgresql:
  auth:
    existingSecret: auth
  
  primary:
    persistence:
      storageClass: openebs-hostpath

  backup:
    enabled: true
    cronjob:
      storage:
        existingClaim: postgresql-backup