apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml

configMapGenerator:
  - name: zwave
    files:
      - settings.json.tmpl
      - nodes.json
    options:
      labels:
        app.kubernetes.io/name: zwave