apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

configMapGenerator:
  - name: zwave2mqtt
    files:
      - settings.json.tmpl
      - nodes.json
      - customDevices.json
    options:
      labels:
        app.kubernetes.io/name: zwave
generatorOptions:
    disableNameSuffixHash: true