apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zwave
  namespace: home-automation
spec:
  encryptedData:
    networkKey: AgAy7eeG5vgWyjWRuSzvQVkmUxzrzco/pSwrHR582hpFS8Vd95FEFthNVIbkOr/UvzxKws2XPo1qwWwvwUNLHpVCJ8KZAsBaZ3zfefvqIoVG7tS6jLTk6NMQc2CXeliClOrgF9c6rFeBs7J2n660sQrB6ELTxIuRD3mpD3pEtyd0mdfGSmdkGlkkPHyqfkJFkcYnq6Eg9zdIbkerAsi/UCSwLGQHTYJi1kw9faM7RxpIRWVjr5QOS0a4+3SI6EXaIVLbP/QU4lFESgpXxIDX+YuB5kOSJeP4NIb7kJs2QCH6VABRfq5FiXXvF4rRzQsxZ4mSWDNpfsdLyh46GjNrWNZubIi2FkMF1HHQj4B89HXfB6Yl1DOKvx+aF4x76udBSDa+5aNG41w37+4IQd7zw3vldmhLmldgDKt/JdApdqSP3XWOyFICTQ9tgN+YJtdJuU5ZEpeQyAJkNH7933A72aG1xWvT6V8okrCiCL2u0JfeSoxkHCGfws7dcPvl/XFTzoOmVE/aoWdt+ryVjR1pdsmcb6XpAdvqz8RlWVVspYVlzn5EgFa0MH9g0aa3FbL4D6v/bV9y5KmpzgOFV7AN9Cwp/WwbjiZxYwNYueWUMRCA5fp7CSufc6D/ce8H9Y3oQ+cC5lws0Gt4e3vLLMix8K4PWsHuERbnf9LcWZ4GO4Qd6vGKK0oG57YRpFPRe3HtWZTfBwJxAbwFUwn0ZuPCx5tG74NuOcHlpZKoGU+pj4YEmi0thK+m8Qu07KuyqhuKDTnQa5J4LEEwZFkFMQQ7xP15shFo7TU+ufxNAjfSjkq2LtjpFiMsRDN/PrQoZh1G
  template:
    metadata:
      name: zwave
      namespace: home-automation

