apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - vwsfriend-externalsecrets.yaml
  - weconnect-externalsecrets.yaml
  - ingress.yaml
  - service.yaml
  - pvc.yaml
