apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - vwsfriend-externalsecrets.yaml
  - weconnect-externalsecrets.yaml
  - vwsfriend-datasource-externalsecrets.yaml
  - ingress.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: vwsfriend-dashboards-internal
    files:
      - grafana/dashboards/Internal/aggregated_trip_details.json
      - grafana/dashboards/Internal/charge_session.json
      - grafana/dashboards/Internal/refuel_session.json
      - grafana/dashboards/Internal/server_statistics.json
      - grafana/dashboards/Internal/trip_details.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"

  - name: vwsfriend-dashboards-1
    files:
      - grafana/dashboards/VWsFriend/charges.json
      - grafana/dashboards/VWsFriend/charging_statistics.json
      - grafana/dashboards/VWsFriend/journey.json
      - grafana/dashboards/VWsFriend/journeys.json
      - grafana/dashboards/VWsFriend/live.json
      - grafana/dashboards/VWsFriend/locations.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"

  - name: vwsfriend-dashboards-2
    files:
      - grafana/dashboards/VWsFriend/maintenance.json
      - grafana/dashboards/VWsFriend/mileage.json
      - grafana/dashboards/VWsFriend/overview.json
      - grafana/dashboards/VWsFriend/refueling.json
      - grafana/dashboards/VWsFriend/statistics.json
      - grafana/dashboards/VWsFriend/trips.json
      - grafana/dashboards/VWsFriend/visited.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"