apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vwsfriend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vwsfriend
