apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vwsfriend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection-string: postgresql://vwsfriend:{{ .db-password }}@postgresql.postgresql:5432/vwsfriend
  data:
    - secretKey: db-password
      remoteRef:
        key: postgresql
        propery: db:vwsfriend-password

  dataFrom:
    - extract:
        key: vwsfriend
