apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vwsfriend-datasource
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          grafana_datasource: 'true'  
      data:
        vwsfriend-db.yaml: |-
          apiVersion: 1
          datasources:
            - name: vwsfriend db
              type: postgres
              url: postgresql.postgresql:5432
              uid: P2EF847825A020B66
              user: vwsfriend
              database: vwsfriend
              secureJsonData:
                password: {{ .dbpassword }}
              jsonData:
                sslmode: "disable"
                postgresVersion: 1500
  data:
    - secretKey: dbpassword
      remoteRef:
        key: postgresql
        property: db:vwsfriend-password
  dataFrom:
    - extract:
        key: vwsfriend
