apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vwsfriend-datasource
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          grafana_datasource: 'true'  
      data:
        vwsfriend-db.yaml: |-
          apiVersion: 1
          datasources:
            - name: vwsfriend db
              type: postgres
              access: proxy
              url: postgresql.postgresql:5432
              uid: P2EF847825A020B66
              user: vwsfriend
              database: vwsfriend
              secureJsonData:
                password: {{ .dbpassword }}
              jsonData:
                sslmode: "disable"
                postgresVersion: 1500
        vwsfriend-live.yaml: |-
          apiVersion: 1
          datasources:
            - name: vwsfriend live
              type: marcusolsson-json-datasource
              uid: P36D08C1A0297C737
              access: proxy
              url: "http://vwsfriend.home-automation:80"
              basicAuth: true
              basicAuthUser: {{ .username }}
              secureJsonData:
                basicAuthPassword: {{ .password }}
              jsonData:
                timeout: 1
  dataFrom:
    - extract:
        key: vwsfriend
