apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vwsfriend
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      data:
        connection-string: "postgresql://vwsfriend:{{ .dbpassword }}@postgresql.postgresql:5432/vwsfriend"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: dbpassword
      remoteRef:
        key: postgresql
        property: db:vwsfriend-password
  dataFrom:
    - extract:
        key: vwsfriend
