apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-red-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: node-red
            port: 
              name: http
    host: node-red.k3s.ingenstans.se
  tls:
    - hosts:
      - node-red.k3s.ingenstans.se
      secretName: node-red-ingress-cert