apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - ingress.yaml
  
configMapGenerator:
  - name: node-red-backup-templates
    files:
      - crontab.tmpl
    options:
      labels:
        app.kubernetes.io/name: node-red