apiVersion: apps/v1
kind: Deployment
metadata:
  name: deconz
  labels:
    app: deconz
    app.kubernetes.io/name: deconz
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deconz
  template:
    metadata:
      labels:
        app: deconz
        app.kubernetes.io/name: deconz 
    spec:
      initContainers:
        - name: init-borg
          image: ghcr.io/mattsve/borgmatic:0.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: deconz
              mountPath: /data
            - name: secrets
              mountPath: /root/.ssh
              readOnly: true
          env:
            - name: TZ
              value: Europe/Stockholm
            - name: REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: deconz
                  key: borg-repo
            - name: PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: deconz
                  key: borg-passphrase
          args:
            - restore
            - -r
            - "'$(REPOSITORY)'"
            - -p 
            - "'$(PASSPHRASE)'"
            - -a 
            - deconz
            - /data
        - name: inject-secrets
          image: hairyhenderson/gomplate:v3.8.0-alpine
          volumeMounts:
            - name: backup-templates
              mountPath: /templates
            - name: backup-config
              mountPath: /config
            - name: backup-secrets
              mountPath: /secrets
          env:
            - name: TZ
              value: Europe/Stockholm
          command: ["sh", "-c"]
          args:
            - gomplate -d secrets=/secrets < /templates/crontab.tmpl > /config/crontab
      containers:
        - name: deconz
          image: marthoc/deconz:amd64-2.05.88
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Stockholm
            - name: DECONZ_DEVICE
              value: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2152763-if00
            - name: DECONZ_WS_PORT
              value: "8080"
            - name: DECONZ_VNC_MODE
              value: "1"
            - name: DECONZ_VNC_PORT
              value: "5900"
            - name: DECONZ_VNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deconz
                  key: vnc-password
          volumeMounts:
            - name: deconz
              mountPath: /root/.local/share/dresden-elektronik/deCONZ
            - name: conbee-device
              mountPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2152763-if00
          securityContext:
            privileged: true
        - name: cron-borg
          image: ghcr.io/mattsve/borgmatic:0.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: deconz
              mountPath: /data
            - name: backup-config
              mountPath: /config
            - name: secrets
              mountPath: /root/.ssh
              readOnly: true
          env:
            - name: TZ
              value: Europe/Stockholm
          args:
            - cron
            - /config/crontab
      volumes:
        - name: deconz
          emptyDir: {}
        - name: backup-config
          emptyDir: {}
        - name: backup-templates
          configMap:
            name: deconz-backup-templates
        - name: conbee-device
          hostPath:
            path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2152763-if00
        - name: secrets
          secret:
            secretName: deconz
            items:
              - key: id_ed25519
                mode: 0600
                path: id_ed25519
              - key: id_ed25519.pub
                mode: 0644
                path: id_ed25519.pub
              - key: known_hosts
                mode: 0644
                path: known_hosts
        - name: backup-secrets
          secret:
            secretName: deconz
            items:
              - key: borg-repo
                mode: 0400
                path: borg-repo
              - key: borg-passphrase
                mode: 0400
                path: borg-passphrase
      nodeSelector:
        conbee: "true"