apiVersion: v1
kind: Service
metadata:
  name: deconz
  annotations:
    external-dns.alpha.kubernetes.io/hostname: deconz.k3s.ingenstans.se.
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: deconz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: websocket
    - protocol: TCP
      port: 5900
      targetPort: 5900
      name: vnc
  type: LoadBalancer
  externalTrafficPolicy: Cluster