apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml

configMapGenerator:
  - name: rfxtrx2mqtt
    files:
      - rfxtrx2mqtt.yaml
    options:
      labels:
        app.kubernetes.io/name: rfxtrx2mqtt