apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mqtt-k3s-ingenstans-se
spec:
  secretName: mqtt-k3s-ingenstans-se-tls
  dnsNames:
    - mqtt.k3s.ingenstans.se
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
