apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - pvc.yaml

configMapGenerator:
  - name: mosquitto
    files:
      - mosquitto.conf
    options:
      labels:
        app.kubernetes.io/name: mosquitto