apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.k3s.ingenstans.se.
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt
    - protocol: TCP
      port: 8883
      targetPort: 8883
      name: mqtt-tls
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: websocket
    - protocol: TCP
      port: 9883
      targetPort: 9883
      name: websocket-tls
  type: LoadBalancer