apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  annotations:
    external-dns.alpha.kubernetes.io/hostname=mosquitto.k3s.ingenstans.se."
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: LoadBalancer