apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml
resources:
  - controller.yaml
    
patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: sealed-secrets-controller
      version: v1
    path: deployment-patch.yaml    
