apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  
configMapGenerator:
  - name: plex
    files:
      - crontab
      - borg-backup.sh
      - getClaimToken.js
    options:
      labels:
        app.kubernetes.io/name: plex