apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
spec:
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0555
    - file_mode=0444
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: plex-data-pv  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//l-space.hem.ingenstans.se/data/media"
    nodeStageSecretRef:
      name: plex-smb
      namespace: htpc