apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-data
  storageClassName: ""