apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex-iot.k3s.ingenstans.se.
    metallb.universe.tf/address-pool: iot
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
      name: mediaserver
  type: LoadBalancer
