apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: logs/app
    repoURL: https://github.com/mattsve/k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
