apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - name: bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
    - name: coredns
      type: helm
      url: https://coredns.github.io/helm
    - name: argocd
      type: helm
      url: https://argoproj.github.io/argo-helm
    - name: csi-driver-smb
      type: helm
      url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    - name: openebs-localpv
      type: helm
      url: https://openebs.github.io/dynamic-localpv-provisioner
    - name: kongz
      type: helm
      url: https://charts.kong-z.com/
    - name: zigbee2mqtt
      type: helm
      url: https://charts.zigbee2mqtt.io