apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
    - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.7.0

resources:
    - base/namespace.yaml
    - base/ingress.yaml
    
patchesJson6902:
  - path: argocd-server-deploy-command.yaml
    target:
        group: apps
        kind: Deployment
        name: argocd-server
        version: v1

namespace: argocd