apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zwavejs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: home-automation
    server: https://kubernetes.default.svc
  project: default
  source:
    path: home-automation/zwavejs
    repoURL: https://github.com/mattsve/k8s
    targetRevision: HEAD
