apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  dataFrom:
    - find:
        path: k3s smb
        name:
          regexp: .*

