# smb-storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-csi
provisioner: smb.csi.k8s.io
parameters:
  source: //l-space.hem.ingenstans.se/k3s
  csi.storage.k8s.io/node-stage-secret-name: smb
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0755
  - file_mode=0644
  - uid=1000
  - gid=1000