apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          env:
            - name: ETCD_URLS
              value: http://etcd.dns.svc.cluster.local:2379
