graylog:
  graylog:
    replicas: 1
    persistence:
      storageClass: openebs-hostpath
    existingRootSecret: graylog
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/redirect-entry-point: https
      hosts:
        - graylog.k3s.ingenstans.se
      tls:
        - hosts:
            - graylog.k3s.ingenstans.se
          secretName: graylog-ingress-cert
    input:
      udp:
        service:
          type: LoadBalancer
          annotations:
            external-dns.alpha.kubernetes.io/hostname: logs.k3s.ingenstans.se.
            metallb.universe.tf/address-pool: default
        ports:
          - name: syslog
            port: 5140
    provisioner:
      enabled: true
      script: |
        #!/bin/bash
        SYSLOG_UDP='
        {
              "global": "true",
              "title": "Syslog UDP",
              "configuration": {
                "port": 5140,
                "bind_address": "0.0.0.0"
              },      
              "type": "org.graylog2.inputs.syslog.udp.SyslogUDPInput"
        }'

        INPUTS=$(curl -X GET -H "Content-Type: application/json" --user "admin:${GRAYLOG_PASSWORD_SECRET}" "http://graylog/api/system/inputs")
        if [ $(echo $INPUTS | grep -c "UDP") != "1" ]; then
            curl -s -X POST -H "Content-Type: application/json" -d "${SYSLOG_UDP}" --user "admin:${GRAYLOG_PASSWORD_SECRET}" "http://graylog/api/system/inputs"
        fi
  
  elasticsearch:
    cluster:
      env:
        RECOVER_AFTER_MASTER_NODES: 1
        EXPECTED_MASTER_NODES: 1
    data:
      persistence:
        storageClass: openebs-hostpath