apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dns/etcd
    repoURL: https://github.com/mattsve/k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true