argocd-notifications:
  secret:
    create: false

  templates:
    - name: app-health-degraded
      webhook:
        telegram:
          method: POST
          body: |
            {
              "parse_mode": "MarkdownV2",
              "text": "Application {{ .app.metadata.name }} has degraded. [Application details]({{.context.argocdUrl}}/applications/{{.app.metadata.name}})"
            }
    - name: app-sync-failed
      webhook:
        telegram:
          method: POST
          body: |
            {
              "parse_mode": "MarkdownV2",
              "text": "The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}} Sync operation details are available [here]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true)."
            }
  
  triggers:
    - name: on-health-degraded
      enabled: true
    - name: on-sync-failed
      enabled: true