argocd-notifications:
  secret:
    create: false

  notifiers: 
    service.slack: ''
    service.telegram: |
      token: $telegram-token

  subscriptions:
    - recipients:    
      - telegram:k3s_status
      triggers:
        - on-health-degraded
        - on-sync-failed
  
  templates:
    template.app-health-degraded: |
      message: |
        ❗️ Application {{ .app.metadata.name }} has degraded.
    template.app-sync-failed: |
      message: |
        ❕ Failed to sync application {{ .app.metadata.name }}.

  triggers:
    trigger.on-health-degraded: |
      - description: Application has degraded        
        send:
          - app-health-degraded
        when: app.status.health.status == 'Degraded'
    trigger.on-sync-failed: |
      - description: Application syncinc has failed
        send:
          - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']