apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-backup
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0770
    - file_mode=0660
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: postgresql-backup-pv  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//l-space.hem.ingenstans.se/data/backup/postgresql"
    nodeStageSecretRef:
      name: smb
      namespace: postgresql