kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: postgresql-backup
  storageClassName: ""