apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
data:  
  updateConfiguration.sh: |
    #!/bin/bash
    for f in /catalog/*-password 
    do 
        user=$(echo "$(basename -- $f)" | sed 's/\(.*\)-password/\1/')
        password=$(cat $f)
        echo "SELECT 'CREATE ROLE $user' WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$user')\gexec" | psql -h postgresql -U postgres
        echo "ALTER ROLE $user WITH LOGIN PASSWORD '$password'" | psql -h postgresql -U postgres
    done
    for f in /catalog/*-databases 
    do 
      user=$(echo "$(basename -- $f)" | sed 's/\(.*\)-databases/\1/')
      while IFS="" read -r l || [ -n "$l" ]
      do
        echo "SELECT 'CREATE DATABASE $l' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$l')\gexec" | psql -h postgresql -U postgres
        echo "GRANT ALL PRIVILEGES ON DATABASE $l TO $user" | psql -h postgresql -U postgres
      done < $f
    done


