apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: letsencrypt@ingenstans.se
        privateKeySecretRef:
            name: letsencrypt-prod-account-key
        solvers:
            - dns01:
                cloudflare: cloudflare@ingenstans.se
                apiTokenSecretRef:
                    name: cloudflare-api-token
                    key: api-token