apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
    - https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml

resources:
    - clusterIssuer.yaml
    - clusterIssuer-staging.yaml
    - cloudflare-api-token.yaml

patchesJson6902:
    - path: recursive-nameservers-patch.yaml
      target:
          group: apps
          kind: Deployment
          name: cert-manager
          namespace: cert-manager
          version: v1