apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: borg-repo
      remoteRef:
        key: esphome
        property: database
    - secretKey: borg-passphrase
      remoteRef:
        key: esphome
        property: password
    - secretKey: id_ed25519
      remoteRef:
        key: Borgbase k3s
        property: private Key
    - secretKey: id_ed25519.pub
      remoteRef:
        key: borgbase k3s
        property: public Key
    - secretKey: known_hosts
      remoteRef:
        key: esphome
        property: known_hosts