apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: node
        operator: Exists